stages:
  - deploy

cache:
  paths:
    - node_modules/

deploy_prod:
  stage: deploy
  image: node:20-alpine
  variables:
    SSH_DEPLOYMENT_NETCUP_PRIVATE_KEY: $SSH_DEPLOYMENT_NETCUP_PRIVATE_KEY
    DEPLOYMENT_DIR: "/var/www/html/mosaikbox"
  before_script:
    - apk add openssh rsync
    - eval $(ssh-agent -s)
    - echo "$SSH_DEPLOYMENT_NETCUP_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan "$DEPLOYMENT_NETCUP_SERVER" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - npm install
    - yarn build:ci
    - ssh "$DEPLOYMENT_NETCUP_USERNAME"@"$DEPLOYMENT_NETCUP_SERVER" "rm -rf $DEPLOYMENT_DIR/*"
    - cd dist
    - rsync -ravR --exclude=".*" . "$DEPLOYMENT_NETCUP_USERNAME"@"$DEPLOYMENT_NETCUP_SERVER":$DEPLOYMENT_DIR
  environment:
    name: production
    url: https://mosaikbox.com
  only:
    - main
  except:
    - schedules
